# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Rubicon-Web\rubicon_web\widgets\top_bar\tab_bar\Ui_tab_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tab_bar(object):
    def setupUi(self, tab_bar):
        tab_bar.setObjectName("tab_bar")
        tab_bar.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tab_bar.sizePolicy().hasHeightForWidth())
        tab_bar.setSizePolicy(sizePolicy)
        tab_bar.setStyleSheet("QWidget {\n"
"    background-color: /tab_bar_bg_color/;\n"
"}\n"
"QTabBar {\n"
"    background: /tab_bar_bg_color/;\n"
"    border: 0px;    \n"
"    color: white;\n"
"}\n"
"QTabBar::tab {\n"
"    background: /tab_bg_color/;\n"
"    border: 2px solid /tab_bar_accent_color/;\n"
"    border-radius: 6px;\n"
"    padding: 4px;\n"
"    margin: 2px;\n"
"    color: /tab_font_color/;\n"
"}\n"
"QTabBar::tab:hover {\n"
"    background-color: /tab_hover_color/;\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: /tab_focus_color/;\n"
"}\n"
"QTabBar::close-button {\n"
"    image: url(*rubicon_web/widgets/top_bar/tab_bar/tabs/svg/close tab button icon.svg*);\n"
"}")
        self.tab_bar_layout = QtWidgets.QHBoxLayout(tab_bar)
        self.tab_bar_layout.setContentsMargins(2, 4, 2, 2)
        self.tab_bar_layout.setSpacing(0)
        self.tab_bar_layout.setObjectName("tab_bar_layout")

        self.retranslateUi(tab_bar)
        QtCore.QMetaObject.connectSlotsByName(tab_bar)

    def retranslateUi(self, tab_bar):
        _translate = QtCore.QCoreApplication.translate
        tab_bar.setWindowTitle(_translate("tab_bar", "Form"))
