# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Rubicon-Web\rubicon_web\widgets\top_bar\nav_bar\Ui_nav_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nav_bar(object):
    def setupUi(self, nav_bar):
        nav_bar.setObjectName("nav_bar")
        nav_bar.resize(1112, 39)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(nav_bar.sizePolicy().hasHeightForWidth())
        nav_bar.setSizePolicy(sizePolicy)
        nav_bar.setAutoFillBackground(True)
        nav_bar.setStyleSheet("QWidget {\n"
"    border: 0px;\n"
"    background-color: rgb(21, 21, 21);\n"
"}\n"
"QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color: /nav_bar_accent_color/;\n"
"    border: 0px;\n"
"    font: 24px \"dripicons-v2\";\n"
"    margin: 2px;\n"
"    padding: 2px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: /nav_bar_hover_color/;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"    padding-top: 4px;\n"
"    padding-left: 4px;\n"
"}\n"
"QLineEdit {\n"
"    background-color: /url_bar_bg_color/;\n"
"    border-radius: 13px;\n"
"    color: rgb(255, 255, 255);\n"
"    padding-left: 8px;\n"
"    padding-bottom: 2px;\n"
"    margin-top: 3px;\n"
"    margin-bottom: 3px;\n"
"    margin-left: 1px;\n"
"    margin-right: 1px;\n"
"    border: 2px solid /nav_bar_accent_color/;\n"
"}\n"
"QLineEdit:hover {\n"
"    background-color: /nav_bar_hover_color/;\n"
"}\n"
"QLineEdit:focus {\n"
"    background-color: /nav_bar_focus_color/;\n"
"}")
        self.nav_bar_layout = QtWidgets.QHBoxLayout(nav_bar)
        self.nav_bar_layout.setContentsMargins(0, 0, 0, 0)
        self.nav_bar_layout.setSpacing(0)
        self.nav_bar_layout.setObjectName("nav_bar_layout")
        self.back_button = QtWidgets.QPushButton(nav_bar)
        self.back_button.setIconSize(QtCore.QSize(23, 23))
        self.back_button.setObjectName("back_button")
        self.nav_bar_layout.addWidget(self.back_button)
        self.forward_button = QtWidgets.QPushButton(nav_bar)
        self.forward_button.setIconSize(QtCore.QSize(23, 23))
        self.forward_button.setObjectName("forward_button")
        self.nav_bar_layout.addWidget(self.forward_button)
        self.reload_and_stop_button = QtWidgets.QPushButton(nav_bar)
        self.reload_and_stop_button.setIconSize(QtCore.QSize(23, 23))
        self.reload_and_stop_button.setObjectName("reload_and_stop_button")
        self.nav_bar_layout.addWidget(self.reload_and_stop_button)
        self.new_tab_button = QtWidgets.QPushButton(nav_bar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.new_tab_button.sizePolicy().hasHeightForWidth()
        )
        self.new_tab_button.setSizePolicy(sizePolicy)
        self.new_tab_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.new_tab_button.setIconSize(QtCore.QSize(18, 18))
        self.new_tab_button.setObjectName("new_tab_button")
        self.nav_bar_layout.addWidget(self.new_tab_button)

        self.retranslateUi(nav_bar)
        QtCore.QMetaObject.connectSlotsByName(nav_bar)

    def retranslateUi(self, nav_bar):
        _translate = QtCore.QCoreApplication.translate
        self.back_button.setText(_translate("nav_bar", "l"))
        self.forward_button.setText(_translate("nav_bar", "m"))
        self.reload_and_stop_button.setText(_translate("nav_bar", "Z"))
        self.new_tab_button.setText(_translate("nav_bar", ""))
