# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\Rubicon-Web\rubicon_web\widgets\top_bar\tab_bar\window_management_buttons\Ui_window_management_buttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window_management_buttons(object):
    def setupUi(self, window_management_buttons):
        window_management_buttons.setObjectName("window_management_buttons")
        window_management_buttons.resize(85, 23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(window_management_buttons.sizePolicy().hasHeightForWidth())
        window_management_buttons.setSizePolicy(sizePolicy)
        window_management_buttons.setLayoutDirection(QtCore.Qt.LeftToRight)
        window_management_buttons.setStyleSheet("QWidget {\n"
"    border: 0px;\n"
"}")
        self.window_management_buttons_layout = QtWidgets.QHBoxLayout(window_management_buttons)
        self.window_management_buttons_layout.setContentsMargins(0, 0, 0, 0)
        self.window_management_buttons_layout.setSpacing(0)
        self.window_management_buttons_layout.setObjectName("window_management_buttons_layout")
        self.mazimize_button = QtWidgets.QPushButton(window_management_buttons)
        self.mazimize_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Code\\Rubicon-Web\\rubicon_web\\widgets\\top_bar\\tab_bar\\window_management_buttons\\png/maximize button icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mazimize_button.setIcon(icon)
        self.mazimize_button.setIconSize(QtCore.QSize(23, 23))
        self.mazimize_button.setObjectName("mazimize_button")
        self.window_management_buttons_layout.addWidget(self.mazimize_button)
        self.minimize_button = QtWidgets.QPushButton(window_management_buttons)
        self.minimize_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Code\\Rubicon-Web\\rubicon_web\\widgets\\top_bar\\tab_bar\\window_management_buttons\\png/minimize button icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_button.setIcon(icon1)
        self.minimize_button.setIconSize(QtCore.QSize(23, 23))
        self.minimize_button.setObjectName("minimize_button")
        self.window_management_buttons_layout.addWidget(self.minimize_button)
        self.close_button = QtWidgets.QPushButton(window_management_buttons)
        self.close_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\Code\\Rubicon-Web\\rubicon_web\\widgets\\top_bar\\tab_bar\\window_management_buttons\\png/close button icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon2)
        self.close_button.setIconSize(QtCore.QSize(23, 23))
        self.close_button.setObjectName("close_button")
        self.window_management_buttons_layout.addWidget(self.close_button)

        self.retranslateUi(window_management_buttons)
        QtCore.QMetaObject.connectSlotsByName(window_management_buttons)

    def retranslateUi(self, window_management_buttons):
        pass
